version: '3.8'

services:
  app:
    build: .
    container_name: cumplimiento_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=cumplimiento_db
      - DB_USERNAME=root
      - DB_PASSWORD=1524
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    depends_on:
      - db
    networks:
      - cumplimiento_network

  db:
    image: mysql:8.0
    container_name: cumplimiento_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cumplimiento_db
      MYSQL_ROOT_PASSWORD: 1524
      MYSQL_PASSWORD: 1524
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cumplimiento_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cumplimiento_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1524
    depends_on:
      - db
    networks:
      - cumplimiento_network

networks:
  cumplimiento_network:
    driver: bridge

volumes:
  dbdata: