version: '3.8'

services:
  app:
    build: .
    container_name: cumplimiento_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
