version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Cumplimiento
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cumplimiento_db
      - DB_USERNAME=root
      - DB_PASSWORD=1524
    depends_on:
      - db
    networks:
      - cumplimiento-network
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cumplimiento_db
      - MYSQL_ROOT_PASSWORD=1524
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cumplimiento-network
    restart: unless-stopped

networks:
  cumplimiento-network:
    driver: bridge

volumes:
  db-data: