version: '3.8'

services:
  app:
    build: .
    container_name: cumplimiento
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cumplimiento_em
      - DB_USERNAME=root
      - DB_PASSWORD=Espumas2025*.

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cumplimiento_em
      MYSQL_ROOT_PASSWORD: Espumas2025*.
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge